plugins {
    id 'application'
    id 'jacoco'
}

dependencies {
    implementation project(':list')
    implementation project(':utilities')
    testImplementation platform('org.junit:junit-bom:5.14.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'org.gradle.sample.Main'
}
